# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x10\x66leetmind.status\x1a\x1bgoogle/protobuf/empty.proto\"V\n\x0eStatusResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x18\n\x10registered_tools\x18\x02 \x03(\t\x12\x16\n\x0e\x64\x61tabase_alive\x18\x03 \x01(\x08\x32V\n\x10\x41gentDiagnostics\x12\x42\n\x06Status\x12\x16.google.protobuf.Empty\x1a .fleetmind.status.StatusResponseB\x18\n\x14\x63om.fleetmind.statusP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.fleetmind.statusP\001'
  _globals['_STATUSRESPONSE']._serialized_start=63
  _globals['_STATUSRESPONSE']._serialized_end=149
  _globals['_AGENTDIAGNOSTICS']._serialized_start=151
  _globals['_AGENTDIAGNOSTICS']._serialized_end=237
# @@protoc_insertion_point(module_scope)
