# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReassignOrder = channel.unary_unary(
                '/fleetmind.tools.ToolService/ReassignOrder',
                request_serializer=tools__pb2.ReassignRequest.SerializeToString,
                response_deserializer=tools__pb2.ReassignResponse.FromString,
                _registered_method=True)
        self.NotifyCustomer = channel.unary_unary(
                '/fleetmind.tools.ToolService/NotifyCustomer',
                request_serializer=tools__pb2.NotifyRequest.SerializeToString,
                response_deserializer=tools__pb2.NotifyResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/fleetmind.tools.ToolService/GetOrderStatus',
                request_serializer=tools__pb2.OrderStatusRequest.SerializeToString,
                response_deserializer=tools__pb2.OrderStatusResponse.FromString,
                _registered_method=True)
        self.GetDriverOverview = channel.unary_unary(
                '/fleetmind.tools.ToolService/GetDriverOverview',
                request_serializer=tools__pb2.DriverOverviewRequest.SerializeToString,
                response_deserializer=tools__pb2.DriverOverviewResponse.FromString,
                _registered_method=True)


class ToolServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReassignOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriverOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReassignOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ReassignOrder,
                    request_deserializer=tools__pb2.ReassignRequest.FromString,
                    response_serializer=tools__pb2.ReassignResponse.SerializeToString,
            ),
            'NotifyCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyCustomer,
                    request_deserializer=tools__pb2.NotifyRequest.FromString,
                    response_serializer=tools__pb2.NotifyResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=tools__pb2.OrderStatusRequest.FromString,
                    response_serializer=tools__pb2.OrderStatusResponse.SerializeToString,
            ),
            'GetDriverOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriverOverview,
                    request_deserializer=tools__pb2.DriverOverviewRequest.FromString,
                    response_serializer=tools__pb2.DriverOverviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleetmind.tools.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleetmind.tools.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReassignOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetmind.tools.ToolService/ReassignOrder',
            tools__pb2.ReassignRequest.SerializeToString,
            tools__pb2.ReassignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetmind.tools.ToolService/NotifyCustomer',
            tools__pb2.NotifyRequest.SerializeToString,
            tools__pb2.NotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetmind.tools.ToolService/GetOrderStatus',
            tools__pb2.OrderStatusRequest.SerializeToString,
            tools__pb2.OrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriverOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetmind.tools.ToolService/GetDriverOverview',
            tools__pb2.DriverOverviewRequest.SerializeToString,
            tools__pb2.DriverOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
